In [3]:
def test():
    return
test()

In [8]:
class Demo:
    def test(self):
        print("test()for the class and method")
        return
obj=Demo()  #object creation
obj.test()  #call for the method

test()for the class and method


In [17]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1 
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact  
p1=Demo1()
p1.fact(5)

120

In [25]:
class Demo2:
    def _init_(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(s):
        return s.p1+s.p2
c1=Demo2()
print(c1._init_(100,200))
c1.add()

None


300

In [6]:
#some inheritance
class Person(object):
   #Constructor
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
#derived class
class Employee(Person):
    def isEmployee(self):
        return True
emp=Person("Yashaswini")
print(emp.getName(),emp.isEmployee())
emp1= Employee("Yash")
print(emp.getName(),emp1.isEmployee())

Yashaswini False
Yashaswini True


In [7]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)
print(array.shape)
print(array.dtype)

[1 2 3 4]
(4,)
int32


In [8]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [9]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [2]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [5]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [6]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,2])

slicing column: [3 6]


In [7]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,1])

slicing column: [2 5]


In [8]:
a1=np.array([(1,2,3),(4,5,6)])m
print("second row:",a1[1])

second row: [4 5 6]


In [10]:
ra1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])

first row: [1 2 3]


In [12]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[5.14249877 4.38084149 7.09782045 6.74130039 6.23538827 4.22572068
 5.86763967 4.2405829  3.72274224 4.5006024 ]
min value= 3.7227422417187674
max value= 7.097820452864601
mean value= 5.215513725324567
median value= 4.821550581692366


In [14]:
# Multiply of 1D arrays
#numpy.dot(x,y)--
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [15]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(4,5),(7,8)])
np.dot(c1,c2)

array([[18, 21],
       [40, 47]])

In [19]:
b1=np.array([(1,5),[6,9]])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

In [2]:
import pandas as pd
dict={"name":["xyz","abc","pqr"],
"EmailID":["xyz@gmail.com","abc@gmail.com","pqr@gmail.com"],
    "MobileNumber":[722684,987469,998745],
        "Address":["Hyd","vizag","vijayawada"]}
b=pd.DataFrame(dict)
print(b)

  name        EmailID  MobileNumber     Address
0  xyz  xyz@gmail.com        722684         Hyd
1  abc  abc@gmail.com        987469       vizag
2  pqr  pqr@gmail.com        998745  vijayawada


In [4]:
b.index=["01","02","03"]
print(b)

   name        EmailID  MobileNumber     Address
01  xyz  xyz@gmail.com        722684         Hyd
02  abc  abc@gmail.com        987469       vizag
03  pqr  pqr@gmail.com        998745  vijayawada
